name: Build gdrive

on:
  push:
    branches:
      - master  # 触发工作流的分支
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码

      - name: Set up Go
        uses: actions/setup-go@v4  # 设置 Go 环境
        with:
          go-version: '1.21'  # 指定 Go 版本

      - name: Build gdrive
        run: |
          # 克隆 gdrive 项目
          git clone https://github.com/prasmussen/gdrive.git
          cd gdrive

          # 初始化 Go 模块
          go mod init github.com/prasmussen/gdrive

          # 下载依赖
          go mod tidy

          # 编译项目
          go build -v -o gdrive .

      - name: Upload artifact
        uses: actions/upload-artifact@v3  # 上传构建产物
        with:
          name: gdrive
          path: gdrive/gdrive  # 上传编译后的二进制文件
