name: Go Build

on:
  push:
    branches:
      - master  # 触发工作流的分支
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码

      - name: Set up Go
        uses: actions/setup-go@v4  # 设置 Go 环境
        with:
          go-version: '1.21'  # 指定 Go 版本

      - name: Initialize Go module
        run: go mod init github.com/prasmussen/gdrive  # 初始化 Go 模块

      - name: Download dependencies
        run: go mod tidy  # 下载依赖

      - name: Build
        run: go build -v .  # 编译项目

      - name: Run tests
        run: go test -v ./...  # 运行测试（如果有测试）
